encyclopedia/urls.py
from django.urls import path

from . import views

app_name = "encyclopedia" 

urlpatterns = [
    path("", views.index, name="index"),
    path("wiki/<str:title>", views.entry, name="entry"),
    path("search/", views.search, name="search_results"),
    path("add/", views.add, name="add"),
    path("edit/<str:title>", views.edit, name="edit"),
    path("random/", views.random_entry, name="random") 
]

wiki/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("encyclopedia.urls"))
]

encyclopedia/models.py
from django.db import models

# Create your models here.

encyclopedia/views.py
import markdown2
import random
from django.shortcuts import render
from django import forms
from django.http import HttpResponseRedirect
from django.urls import reverse
from . import util

def index(request):
    return render(request, "encyclopedia/index.html", {
        "entries": util.list_entries()
    })

def entry(request, title):
    entry_content = util.get_entry(title)

    if entry_content is not None:
        html_content = markdown2.markdown(entry_content)
        return render(request, "encyclopedia/entry.html", {
            "title": title,
            "content": html_content
        })
    else:
        return render(request, "encyclopedia/error.html", {
            "title": "Page not found",
            "content": "The requested page could not be found."
        })


def search(request):
    query = request.GET.get('q')
    entries = util.list_entries()

    exact_match = next((entry for entry in entries if entry.lower() == query.lower()), None)

    if exact_match:
        entry_content = util.get_entry(exact_match)
        html_content = markdown2.markdown(entry_content)
        return render(request, "encyclopedia/entry.html", {
            "title": exact_match,
            "content": html_content
        })
    else: #subtring matches
        substring_matches = [entry for entry in entries if query.lower() in entry.lower()]
        if substring_matches:
            return render(request, "encyclopedia/search_results.html", {
                "query": query,
                "results": substring_matches
            })
        else:
            # no exact matches or substrings
            return render(request, "encyclopedia/error.html", {
                "title": "Search not found",
                "content": "Please, search again"
            })

class NewPageForm(forms.Form):
    title = forms.CharField(
        label="Write the title",
        max_length=100,
        widget=forms.TextInput(attrs={'style': 'display: block;'})
    )
    content = forms.CharField(
        label="Write the content",
        widget=forms.Textarea(attrs={'style': 'max-height: 50vh; max-width: 80%; display: block;'})
    )

def add(request):
    if request.method == "POST":
        form = NewPageForm(request.POST)
        if form.is_valid():
            title = form.cleaned_data['title']
            content = form.cleaned_data['content']

            entries = util.list_entries()

            if title.lower() in [entry.lower() for entry in entries]:
                return render(request, "encyclopedia/error.html", {
                    "title": "Duplicate Entry",
                    "content": "An entry with the same title already exists. Please choose a different title."
                })
            util.save_entry(title, content)
            return HttpResponseRedirect(reverse("encyclopedia:entry", args=[title]))
        else:
            return render(request, "encyclopedia/add.html", {"form": form})
    
    return render(request, "encyclopedia/add.html", {"form": NewPageForm()})

def random_entry(request):
    entries = util.list_entries()
    random_entry = random.choice(entries)
    entry_content = util.get_entry(random_entry)
    html_content = markdown2.markdown(entry_content)
    return render(request, "encyclopedia/entry.html", {
        "title": random_entry,
        "content": html_content
    })

class EditPageForm(forms.Form):
    content = forms.CharField(
        label="Edit the content",
        widget=forms.Textarea(attrs={'style': 'max-height: 50vh; max-width: 80%; display: block;'})
    )

def edit(request, title):
    entry_content = util.get_entry(title)

    if entry_content is not None:
        if request.method == "POST":
            form = EditPageForm(request.POST)
            if form.is_valid():
                new_content = form.cleaned_data['content']
                util.save_entry(title, new_content)
                return HttpResponseRedirect(reverse("encyclopedia:entry", args=[title]))
        else:
            form = EditPageForm(initial={'content': entry_content})

        return render(request, "encyclopedia/edit.html", {
            "title": title,
            "form": form
        })
    else:
        return render(request, "encyclopedia/error.html", {
            "title": "Page not found",
            "content": "The requested page could not be found."
        })

encyclopedia/templates/encyclopedia/add.html
{% extends "encyclopedia/layout.html" %}

{% block title %}
    Add page
{% endblock %}

{% block body %}
    <h3>Add New Page</h3>
    <form action="{% url 'encyclopedia:add' %}" method="post">
        {% csrf_token %}
        {{ form  }}
        <input type="submit" value="Submit">
    </form>   
{% endblock %}

encyclopedia/templates/encyclopedia/edit.html
<!-- edit.html -->

{% extends "encyclopedia/layout.html" %}

{% block title %}
    Edit - {{ title }}
{% endblock %}

{% block body %}
    <h3>Edit Page</h3>
    <form action="{% url 'encyclopedia:edit' title %}" method="post">
        {% csrf_token %}
        {{ form }}
        <input type="submit" value="Save Changes">
    </form>
{% endblock %}

encyclopedia/templates/encyclopedia/entry.html
{% extends "encyclopedia/layout.html" %}

{% block title %}
    {{ title }}
{% endblock %}

{% block body %}
    {{ content | safe }}
    <a href="{% url 'encyclopedia:edit' title %}">Edit Content</a>
{% endblock %}

encyclopedia/templates/encyclopedia/error.html
{% extends "encyclopedia/layout.html" %}

{% block title %}
    Error
{% endblock %}

{% block body %}
    <h1>{{title}}</h1>
    {{ content | safe }}
{% endblock %}

encyclopedia/templates/encyclopedia/index.html
{% extends "encyclopedia/layout.html" %}

{% block title %}
    Encyclopedia
{% endblock %}

{% block body %}
    <h1>All Pages</h1>

    <ul>
        {% for entry in entries %}
            <li><a href="wiki/{{entry}}">{{ entry }}</a></li>
        {% endfor %}
    </ul>

{% endblock %}

encyclopedia/templates/encyclopedia/layout.html
{% load static %}

<!DOCTYPE html>

<html lang="en">
    <head>
        <title>{% block title %}{% endblock %}</title>
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
        <link href="{% static 'encyclopedia/styles.css' %}" rel="stylesheet">
    </head>
    <body>
        <div class="row">
            <div class="sidebar col-lg-2 col-md-3">
                <h2>Wiki</h2>

                <form action="{% url 'encyclopedia:search_results' %}" method="GET">
                    <input class="search" type="text" name="q" placeholder="Search Encyclopedia">
                </form>
                
                <div>
                    <a href="{% url 'encyclopedia:index' %}">Home</a>
                </div>
                <div>
                    <a href="{% url 'encyclopedia:add' %}">Create New Page</a>
                </div>
                <div>
                    <a href="{% url 'encyclopedia:random' %}">Random Page</a>
                </div>
                {% block nav %}
                {% endblock %}
            </div>
            <div class="main col-lg-10 col-md-9">
                {% block body %}
                {% endblock %}
            </div>
        </div>

    </body>
</html>

encyclopedia/templates/encyclopedia/search_results.html
{% extends "encyclopedia/layout.html" %}

{% block title %}
    Search Results for "{{ query }}"
{% endblock %}

{% block body %}
    <h3>Search Results for "{{ query }}"</h3>
    {% if results %}
        <ul>
            {% for result in results %}
                <li><a href="{% url 'encyclopedia:entry' title=result %}">{{ result }}</a></li>
            {% endfor %}
        </ul>
    {% endif %}
{% endblock %}